export const ADD_TO_CART = "ADD_TO_CART";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";

export const CART_PLACE_ORDER_REQUEST = "CART_PLACE_ORDER_REQUEST";
export const CART_PLACE_ORDER_SUCCESS = "CART_PLACE_ORDER_SUCCESS";
export const CART_PLACE_ORDER_FAILED = "CART_PLACE_ORDER_FAILED";


export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED";