export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";
export const SORT_COLLECTION_ALPHABETICAL_ASC = "SORT_COLLECTION_ALPHABETICAL_ASC";
export const SORT_COLLECTION_ALPHABETICAL_DESC = "SORT_COLLECTION_ALPHABETICAL_DESC";
export const SORT_COLLECTION_PRICE_ASC = "SORT_COLLECTION_PRICE_ASC";
export const SORT_COLLECTION_PRICE_DESC = "SORT_COLLECTION_PRICE_DESC";


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILED = "PRODUCT_DETAILS_FAILED";

export const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST";
export const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_SUCCESS";
export const PRODUCT_SAVE_FAILED = "PRODUCT_SAVE_FAILED";


export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED";

export const PRODUCT_REVIEW_SUBMIT_REQUEST = "PRODUCT_REVIEW_SUBMIT_REQUEST";
export const PRODUCT_REVIEW_SUBMIT_SUCCESS = "PRODUCT_REVIEW_SUBMIT_SUCCESS";
export const PRODUCT_REVIEW_SUBMIT_FAILED = "PRODUCT_REVIEW_SUBMIT_FAILED";
export const PRODUCT_REVIEW_SUBMIT_RESET = 'PRODUCT_REVIEW_SUBMIT_RESET';

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAILED = "REVIEW_DELETE_FAILED";

export const REVIEW_DETAILS_REQUEST = "REVIEW_DETAILS_REQUEST";
export const REVIEW_DETAILS_SUCCESS = "REVIEW_DETAILS_SUCCESS";
export const REVIEW_DETAILS_FAILED = "REVIEW_DETAILS_FAILED";


export const RATING_SUBMIT_REQUEST = "RATING_SUBMIT_REQUEST";
export const RATING_SUBMIT_SUCCESS = "RATING_SUBMIT_SUCCESS";
export const RATING_SUBMIT_FAILED = "RATING_SUBMIT_FAILED";